kind: pipeline
type: kubernetes
name: default

# only build on tags
trigger:
  event:
    - tag

steps:
  - name: build
    image: quay.io/buildah/stable:latest
    environment:
      # get registry credentials from orgsecrets
      REGISTRY_USERNAME:
        from_secret: registry_username
      REGISTRY_PASSWORD:
        from_secret: registry_password
      # get WEE_VERSION build arg from DRONE_TAG env var
      WEE_VERSION: ${DRONE_TAG##v}
    # can't find a way to get buildah to work right with fuse-overlayfs in unprivileged mode
    privileged: true
    commands:
      - buildah login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.hubbe.club
      - buildah bud --build-arg WEE_VERSION=$WEE_VERSION --tag registry.hubbe.club/weechat:$DRONE_TAG --tag registry.hubbe.club/weechat:latest .
      - buildah push registry.hubbe.club/weechat:$DRONE_TAG
      - buildah push registry.hubbe.club/weechat:latest
    resources:
      requests:
        cpu: 100
        memory: 100MiB
      limits:
        cpu: 500
        memory: 500MiB
