version: '3'
services:
  weechat:
    image: hubbeking/weechat
    container_name: weechat
    restart: unless-stopped
    ports:
      - 9001:9001
    volumes:
      - ./weechat/:/home/weechat/.weechat/
      - ./tmux.conf:/home/weechat/.tmux.conf
